// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.file;

import edu.unlv.cs.rebelhotel.file.UploadProgress;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect FileUploadDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FileUploadDataOnDemand: @Component;
    
    private Random FileUploadDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<UploadProgress> FileUploadDataOnDemand.data;
    
    public UploadProgress FileUploadDataOnDemand.getNewTransientUploadProgress(int index) {
        edu.unlv.cs.rebelhotel.file.UploadProgress obj = new edu.unlv.cs.rebelhotel.file.UploadProgress();
        obj.setFileUploadStatus(null);
        obj.setMessage("message_" + index);
        obj.setSuccessful(Boolean.TRUE);
        obj.setStartOfExecution(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setEndOfExecution(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public UploadProgress FileUploadDataOnDemand.getSpecificUploadProgress(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        UploadProgress obj = data.get(index);
        return UploadProgress.findUploadProgress(obj.getId());
    }
    
    public UploadProgress FileUploadDataOnDemand.getRandomUploadProgress() {
        init();
        UploadProgress obj = data.get(rnd.nextInt(data.size()));
        return UploadProgress.findUploadProgress(obj.getId());
    }
    
    public boolean FileUploadDataOnDemand.modifyUploadProgress(UploadProgress obj) {
        return false;
    }
    
    public void FileUploadDataOnDemand.init() {
        data = edu.unlv.cs.rebelhotel.file.UploadProgress.findUploadProgressEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'UploadProgress' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<edu.unlv.cs.rebelhotel.file.UploadProgress>();
        for (int i = 0; i < 10; i++) {
            edu.unlv.cs.rebelhotel.file.UploadProgress obj = getNewTransientUploadProgress(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
