// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import java.lang.Integer;

privileged aspect Progress_Roo_JavaBean {
    
    public Integer Progress.getTotalHours() {
        return this.totalHours;
    }
    
    public void Progress.setTotalHours(Integer totalHours) {
        this.totalHours = totalHours;
    }
    
}
