// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.unlv.cs.rebelhotel.domain;

import edu.unlv.cs.rebelhotel.domain.RandomValidationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RandomValidationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RandomValidationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RandomValidationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RandomValidationIntegrationTest: @Transactional;
    
    @Autowired
    private RandomValidationDataOnDemand RandomValidationIntegrationTest.dod;
    
    @Test
    public void RandomValidationIntegrationTest.testCountRandomValidations() {
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", dod.getRandomRandomValidationBatch());
        long count = RandomValidationBatch.countRandomValidations();
        org.junit.Assert.assertTrue("Counter for 'RandomValidation' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RandomValidationIntegrationTest.testFindRandomValidation() {
        RandomValidationBatch obj = dod.getRandomRandomValidation();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to provide an identifier", id);
        obj = RandomValidationBatch.findRandomValidation(id);
        org.junit.Assert.assertNotNull("Find method for 'RandomValidation' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'RandomValidation' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RandomValidationIntegrationTest.testFindAllRandomValidations() {
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", dod.getRandomRandomValidation());
        long count = RandomValidationBatch.countRandomValidations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'RandomValidation', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<RandomValidationBatch> result = RandomValidationBatch.findAllRandomValidations();
        org.junit.Assert.assertNotNull("Find all method for 'RandomValidation' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'RandomValidation' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RandomValidationIntegrationTest.testFindRandomValidationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", dod.getRandomRandomValidation());
        long count = edu.unlv.cs.rebelhotel.domain.RandomValidation.countRandomValidations();
        if (count > 20) count = 20;
        java.util.List<edu.unlv.cs.rebelhotel.domain.RandomValidation> result = edu.unlv.cs.rebelhotel.domain.RandomValidation.findRandomValidationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'RandomValidation' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'RandomValidation' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RandomValidationIntegrationTest.testFlush() {
        edu.unlv.cs.rebelhotel.domain.RandomValidation obj = dod.getRandomRandomValidation();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.RandomValidation.findRandomValidation(id);
        org.junit.Assert.assertNotNull("Find method for 'RandomValidation' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRandomValidation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'RandomValidation' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RandomValidationIntegrationTest.testMerge() {
        edu.unlv.cs.rebelhotel.domain.RandomValidation obj = dod.getRandomRandomValidation();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to provide an identifier", id);
        obj = edu.unlv.cs.rebelhotel.domain.RandomValidation.findRandomValidation(id);
        boolean modified =  dod.modifyRandomValidation(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        edu.unlv.cs.rebelhotel.domain.RandomValidation merged = (edu.unlv.cs.rebelhotel.domain.RandomValidation) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'RandomValidation' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RandomValidationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", dod.getRandomRandomValidation());
        RandomValidationBatch obj = dod.getNewTransientRandomValidation(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'RandomValidation' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'RandomValidation' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RandomValidationIntegrationTest.testRemove() {
        RandomValidationBatch obj = dod.getRandomRandomValidation();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'RandomValidation' failed to provide an identifier", id);
        obj = RandomValidationBatch.findRandomValidation(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'RandomValidation' with identifier '" + id + "'", RandomValidationBatch.findRandomValidation(id));
    }
    
}
